// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACDhbkbIUcps8DZVqfQi_7G2qfpuqej6Q',
    appId: '1:473882346720:web:eff118b32456d0adf83c85',
    messagingSenderId: '473882346720',
    projectId: 'pab-steven',
    authDomain: 'pab-steven.firebaseapp.com',
    storageBucket: 'pab-steven.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpTukvzqKc4f7mw1i3S8CwwxbYQLbPNNw',
    appId: '1:473882346720:android:527c21d039e24c53f83c85',
    messagingSenderId: '473882346720',
    projectId: 'pab-steven',
    storageBucket: 'pab-steven.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8nGzc6OeAWCbbNzHLEYWIBhOa09hRkwE',
    appId: '1:473882346720:ios:65732d50f677287df83c85',
    messagingSenderId: '473882346720',
    projectId: 'pab-steven',
    storageBucket: 'pab-steven.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8nGzc6OeAWCbbNzHLEYWIBhOa09hRkwE',
    appId: '1:473882346720:ios:65732d50f677287df83c85',
    messagingSenderId: '473882346720',
    projectId: 'pab-steven',
    storageBucket: 'pab-steven.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACDhbkbIUcps8DZVqfQi_7G2qfpuqej6Q',
    appId: '1:473882346720:web:cd4ae30e19e5b23af83c85',
    messagingSenderId: '473882346720',
    projectId: 'pab-steven',
    authDomain: 'pab-steven.firebaseapp.com',
    storageBucket: 'pab-steven.firebasestorage.app',
  );

}